export const ActionTypes = {
  SET_USER: "SET_USER",
  LOG_OUT: "LOG_OUT",
  ADD_PRODUCT_IN_CART: "ADD_PRODUCT_IN_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  MAKE_CART_EMPTY: "MAKE_CART_EMPTY",
  SET_CART: "SET_CART",
  SET_ORDER: "SET_ORDER",
  SET_ORDERS: "SET_ORDERS",
};
